### ISSUE TITLE
视频无法显示

### ISSUE THREAD

**Issue by vic233333** [BetterNCM/BGEnhanced#10]
如题，无论是mp4还是webm格式均无法播放。视频资源能够打开但是预览显示为透明的黑色，且无法正常加载到背景。
该功能在从MoTheme中拆出来之前还是正常的。
静态背景能够正常加载并显示，只有视频无法显示，已排除中文路径bug。
网易云音乐界面，以及使用的插件如图：
<img width="1120" alt="Snipaste_2023-01-26_01-38-22" src="https://user-images.githubusercontent.com/93087330/214640021-398babdc-1755-4a80-aed3-675f07d96585.png">
控制台报错输出如图，希望有帮助：
<img width="1107" alt="Snipaste_2023-01-26_01-32-34" src="https://user-images.githubusercontent.com/93087330/214639033-e6cd893a-1557-445a-add8-cbc1c840f475.png">

**Comment by MicroCBer** [comment]
该功能从来不是从 MoTheme 拆分出来的也与 MoTheme 没有任何关系。

**Comment by MicroCBer** [comment]
本地图片可以加载吗

**Comment by vic233333** [comment]
本地图片可以正常加载，仅图片存在问题。

**Comment by MicroCBer** [comment]
> 本地图片可以正常加载，仅图片存在问题。

按 F12 单击 Console 截图

**Comment by jksndk** [comment]
问题同上，报错也同上（尴尬）

**Comment by jksndk** [comment]
<img width="1280" alt="屏幕截图 2023-01-26 224300" src="https://user-images.githubusercontent.com/83121244/214865166-2a7732dc-3224-4fe9-a8e2-1dd671b0b7ff.png">

**Comment by MicroCBer** [comment]
看不出来啥 群内找我远程吧

**Comment by vic233333** [comment]
> 

问问什么群，我也想加一下

**Comment by MicroCBer** [comment]
> > 
> 
> 问问什么群，我也想加一下

B站私信我的自动回复，这里就不发了

**Comment by jksndk** [comment]
把betterNCM更新成测试版就解决了（
不知道为啥

**Comment by MicroCBer** [comment]
> 把betterNCM更新成测试版就解决了（ 不知道为啥

将 BetterNCM 更新到 nightly 通道可以解决的是 `fs.mountFile` api 不存在的问题和 `openFileDialog` api 不支持特殊符号路径的问题。而这两个问题表现出的性状都与是否为视频无关。此问题描述 `静态背景能够正常加载并显示，只有视频无法显示，已排除中文路径 bug` 显然不是这两个问题。所以你的 `问题同上，报错也同上` 并不是真实准确的问题描述。只有真实准确的问题描述可以帮助我们解决问题。

**Comment by MicroCBer** [comment]
#8 

> 把betterNCM更新成测试版就解决了（ 不知道为啥

#8

**Comment by jksndk** [comment]
抱歉，测试下来发现是视频文件是中文名的原因，不够细心提供了错误描述，对此我深表歉意，下次一定会注意
