### ISSUE TITLE
自定义背景无法加载

### ISSUE THREAD

**Issue by zouyua** [BetterNCM/BGEnhanced#13]
本地图片背景无法加载

![屏幕截图 2023-01-26 205656](https://user-images.githubusercontent.com/116532561/214841274-5b5c3797-cd71-4370-8bd7-716cd4f36fbb.png)
![屏幕截图 2023-01-26 210034](https://user-images.githubusercontent.com/116532561/214841914-c4e81468-0881-449a-952d-c055efeacd46.png)
![屏幕截图 2023-01-26 205847](https://user-images.githubusercontent.com/116532561/214841932-2dfe5cc6-75c1-4c9e-8c69-61141a363b4e.png)

**Comment by MicroCBer** [comment]
#8
