### ISSUE TITLE
背景的模糊方法似乎存在问题？

### ISSUE THREAD

**Issue by YiQuSi** [BetterNCM/BGEnhanced#14]
不太了解相关专业知识，只能随便说说了。

就比如这张图，背景图边缘可以隐约看见MoTheme的默认背景图。
而按照图上的这个缩放值，图片在未模糊状态下应该是刚好完全覆盖窗口的。
![forissue](https://user-images.githubusercontent.com/46985166/215069872-ca87c96f-e1c1-4710-b11b-e94b77dece2b.png)
总之我个人看上去觉得不太合理，要是没问题那就算了。
可以排除是MoTheme的问题，不安装主题插件时模糊的背景图周围会出现黑色。
（这张图是随机二次元里面的）

**Comment by MicroCBer** [comment]
建议自行查看高斯模糊相关知识，浏览器对高斯模糊边界点的处理就是无图片处直接按纯透明算，也就导致边界点的透明度并不为0。这也是为什么我提供了缩放选项。
