### ISSUE TITLE
[bug] 在线图片功能的性能问题

### ISSUE THREAD

**Issue by modenicheng** [BetterNCM/BGEnhanced#17]
使用 BGEnhanced 最新版本和 MoTheme 最新版本 BetterNCM 1.0.0

因为无法加载本地图片（当时没看issue），我把图片都上传到图床了，一次设置了十来张“在线图片”。然后每次我进入插件配置界面，CPU占用可以到45%（Intel i7-11370H）；即使不进行任何操作，只要停留在这个界面就会有30%以上的CPU占用。

**Comment by modenicheng** [comment]
把所有的在线图片都删掉之后性能占用就正常了

**Comment by modenicheng** [comment]
在重新安装了 BetterNCM-nightly 之后得到了解决

> 不知道为什么，我BetterNCM版本是1.0.0稳定版但是就是有问题，加载不出来图片，重装之后所有已经安装的插件全部失效，重新安装了插件之后解决了问题

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215660142-88b73755-119b-4a8f-82fb-b1ed591191f6.png)
无法复现，可以参照 https://github.com/MicroCBer/BetterNCM/issues/236#issuecomment-1401362539 的方法提供性能分析

**Comment by ZSCCFFLP** [comment]
我也遇到了相似的问题，使用 BGEnhanced 最新版本和 MoTheme 最新版本 BetterNCM 1.0.0，问题出现在从旧版BGEnhanced 更新到新版BGEnhanced 后，原来的版本无任何问题，但新版无法正常加载本地文件路径的任何视频和图片文件，经排除无文件路径特殊字符的问题，在线文件加载正常，就是无法显示本地文件（视频和图片）

**Comment by ZSCCFFLP** [comment]
我也遇到了相似的问题，使用 BGEnhanced 最新版本和 MoTheme 最新版本 BetterNCM 1.0.0，问题出现在从旧版BGEnhanced 更新到新版BGEnhanced 后，原来的版本无任何问题，但新版无法正常加载本地文件路径的任何视频和图片文件，经排除无文件路径特殊字符的问题，在线文件加载正常，就是无法显示本地文件（视频和图片）

**Comment by MicroCBer** [comment]
> 我也遇到了相似的问题，使用 BGEnhanced 最新版本和 MoTheme 最新版本 BetterNCM 1.0.0，问题出现在从旧版BGEnhanced 更新到新版BGEnhanced 后，原来的版本无任何问题，但新版无法正常加载本地文件路径的任何视频和图片文件，经排除无文件路径特殊字符的问题，在线文件加载正常，就是无法显示本地文件（视频和图片）

相似锤子 你仔细看看这问题是什么。。。。

你这是 #8

**Comment by MicroCBer** [comment]
can't repro
