### ISSUE TITLE
[Bug]无法显示视频

### ISSUE THREAD

**Issue by int-PP** [BetterNCM/BGEnhanced#18]
无法显示视频壁纸，以前版本是可以的，这次更新之后就不行了
![GWB9TWPY8OGE$KF9UO}D@H](https://user-images.githubusercontent.com/105854929/215818021-c676dbf4-c17d-40d1-ba8f-22003c8e6707.png)
导入视频直接显示为灰色，无法使用
![I$(A WN1QH C I@5DD{$)K](https://user-images.githubusercontent.com/105854929/215818285-f77095b1-4c67-4a42-9a7a-1b0c625472c3.png)
这个视频之前是可以使用

**Comment by MicroCBer** [comment]
#8
