### ISSUE TITLE
优化透明材质背景实现逻辑

### ISSUE THREAD

**Issue by Ds1nk** [BetterNCM/BGEnhanced#2]
将整个屏幕截图并模糊，并将网易云窗口所在的部分裁剪出来并当作背景（或者将图片铺在网易云窗口背景层并隐藏窗口之外的部分）
当屏幕显示内容变化，重新截图并重复上述步骤
当背景变化过于快，用一个真正透明的图片当背景并降低亮度

悄悄告诉你，其实paint.net有个插件叫做alpha模糊，可以将一张透明的图片变成模糊的透明图片
只要把模糊分成不多的等级就能用这个方法实现

**Comment by MicroCBer** [comment]
现在就是 `将整个屏幕截图并模糊，并将网易云窗口所在的部分裁剪出来并当作背景（或者将图片铺在网易云窗口背景层并隐藏窗口之外的部分）`

不太能理解你说的 ⌈ 真正透明的图片 ⌋ 是什么意思
