### ISSUE TITLE
无法加载自定义的图片[jpg png格式都不行]

### ISSUE THREAD

**Issue by YuSanr** [BetterNCM/BGEnhanced#3]
版本
![I%QWNSR%49TJ8GEGG ZDBV3](https://user-images.githubusercontent.com/112278452/213909429-716bc3c2-3b96-430a-92bf-a194b124f45d.png)
加载图片:
![I%QWNSR%49TJ8GEGG ZDBV3](https://user-images.githubusercontent.com/112278452/213909429-716bc3c2-3b96-430a-92bf-a194b124f45d.png)
希望赶快修复
之前版本没这个问题
结果昨天有一个plugin炸了直接给我全之前下的插件全删了导致我被迫更新
然后就无法加载自己的图片了emm

**Comment by YuSanr** [comment]
em 复制错了
加载图片是
![_9BH748P`7Z6VS{Z5NY2T0J](https://user-images.githubusercontent.com/112278452/213909472-b6d0ba51-39b7-4aad-834c-9d0d5946ee1e.png)

**Comment by YuriBrightan** [comment]
同问这个问题

**Comment by 2055135** [comment]
同问，但我这是视频无法加载，图片能加载

**Comment by YuSanr** [comment]
在0.22这个版本中 任然未修复这个问题[提交时是0.21]

**Comment by YuSanr** [comment]
已解决 
使用纯英文目录即可
cao
