### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by hmr233** [BetterNCM/BGEnhanced#30]
版本：0.3.1
更新时间：2023.7.26
啥都不显示
![截图-2023-07-26 17时16分29秒033](https://github.com/BetterNCM/BGEnhanced/assets/67228631/d4a8cd41-8313-48df-81b8-1ff1a9393a5f)

**Comment by curtain1234** [comment]
一样的问题

**Comment by 3101049509** [comment]
一样
