### ISSUE TITLE
插件出bug了

### ISSUE THREAD

**Issue by Nameless0477** [BetterNCM/BGEnhanced#31]
播放器页面变为默认的那张图片了
无法进行修改
<img width="785" alt="1690417946085" src="https://github.com/BetterNCM/BGEnhanced/assets/120151859/7d0215c5-3ded-4f2c-a57d-41b707cfda1e">

**Comment by oahgnay** [comment]
我直接整个插件界面都是空白的
<img width="883" alt="屏幕截图 2023-07-27 175437" src="https://github.com/BetterNCM/BGEnhanced/assets/106806067/f543469d-498b-4813-8eaf-40cf935982be">

**Comment by oahgnay** [comment]
我的插件界面直接空白一片
<img width="883" alt="image" src="https://github.com/BetterNCM/BGEnhanced/assets/106806067/ff408ebb-8d01-4ebe-bbde-7b9ce47b7147">
