### ISSUE TITLE
更新了之后设置面板没了.......

### ISSUE THREAD

**Issue by Nameless0477** [BetterNCM/BGEnhanced#32]
不知道是不是我的问题，我重装了BGEnhanced几次也还是这样
<img width="663" alt="1690458854739" src="https://github.com/BetterNCM/BGEnhanced/assets/120151859/f27cd29d-5ad3-4f5f-b725-c12f88abbbb4">

**Comment by dogdie233** [comment]
我也

**Comment by 1563473280** [comment]
这个问题可以通过清除全部插件再重新安装此插件进行解决。
