### ISSUE TITLE
无法添加背景

### ISSUE THREAD

**Issue by sycapple** [BetterNCM/BGEnhanced#37]
BetterNCM的版本是 1.3.2
无法自主添加本机背景，只能使用提供的背景

**Comment by sycapple** [comment]
网易云版本为2.10.12 x86

**Comment by sycapple** [comment]
![image](https://github.com/BetterNCM/BGEnhanced/assets/89971677/726a33cf-4d18-4827-a571-72724df9fc0d)
添加自己的背景后无法显示

**Comment by sycapple** [comment]
![Uploading 1703584115797.png…]()
添加自己的背景后无法显示

**Comment by sycapple** [comment]
添加自己的背景后无法显示
![1703584115797](https://github.com/BetterNCM/BGEnhanced/assets/89971677/ee92f885-ae52-4e12-9879-e376e17cf3b7)

**Comment by youhunluanma** [comment]
插眼，同样问题

**Comment by MXbfs** [comment]
无法添加本机图片
网易云版本:2.10.10
BetterNCM版本:1.3.2

**Comment by shiguang005** [comment]
插眼，同样的问题

**Comment by ElterZZ** [comment]
#8 图片也只能纯英文目录

**Comment by MicroCBer** [comment]
图片也只能纯英文目录
