### ISSUE TITLE
新版本缺少随机更换壁纸功能

### ISSUE THREAD

**Issue by MisakaOvOMikoto** [BetterNCM/BGEnhanced#4]
首先感谢大大制作的美化插件，我之前一股脑添加了几十张视频壁纸，每次开机都能随机切换。但我发现更新插件后好像没有这个功能了，只能手动选择，希望未来能够改善一下！

**Comment by MicroCBer** [comment]
已完成
![image](https://user-images.githubusercontent.com/66859419/214561355-700e3786-8b9a-4f47-81b0-5900ae2b5105.png)
![image](https://user-images.githubusercontent.com/66859419/214561379-91dd0eaa-e9ae-4afa-ab39-fdd0397a97bc.png)
