### ISSUE TITLE
无法加载自定义视频

### ISSUE THREAD

**Issue by MisakaOvOMikoto** [BetterNCM/BGEnhanced#5]
插件版本：![image](https://user-images.githubusercontent.com/95963109/213920640-c42c9629-dba0-43d0-b2df-7b55ba09a554.png)

导入的视频无法加载：
![image](https://user-images.githubusercontent.com/95963109/213920663-ed057862-407a-4c74-9eb6-cda101b70c0d.png)

**Comment by kikozz** [comment]
same，同样还无法加载图片

**Comment by leonliam** [comment]
同上，希望加回用专辑封面背景的功能

**Comment by MicroCBer** [comment]
#8
