### ISSUE TITLE
新版本的问题

### ISSUE THREAD

**Issue by leonliam** [BetterNCM/BGEnhanced#7]
1和motheme配合的不好，感觉无法同时使用
2用此插件时图片文件会损坏导致加载不了
3失去了用专辑封面当背景的功能
4请问可以下载老版本插件使用吗

**Comment by MicroCBer** [comment]
1. 请更新 MoTheme
2. 请更新 BetterNCM 至 1.0.0-nightly （测试通道） 或使用不包含特殊字符的文件路径。
3. 请更新 BGEnhanced
