### ISSUE TITLE
还是新版本自定义图片无效的问题

### ISSUE THREAD

**Issue by YuriBrightan** [BetterNCM/BGEnhanced#8]
看大家和我问题一样的都换全英文目录解决了，我这里还是这个情况
确定真的是纯英文目录
已经把图片直接扔到根目录下了 D:\1.jpg
还是导入空白...
还有没有别的原因呢

**Comment by hv0905** [comment]
同，目前本地图片、视频均无法载入

**Comment by huajianyizou** [comment]
同，目前本地图片、视频均无法载入

**Comment by emmmmm-qin** [comment]
同无法加载显示

**Comment by hv0905** [comment]
相关的报错：
![image](https://user-images.githubusercontent.com/29349119/214274737-6ad1557a-7aef-4fc0-84c2-1de2c07123e8.png)
另附`fs`上下文与版本：

![image](https://user-images.githubusercontent.com/29349119/214275057-1af0fc56-a379-4213-bf18-cc2d04aaea2b.png)

**Comment by MicroCBer** [comment]
> 相关的报错： ![image](https://user-images.githubusercontent.com/29349119/214274737-6ad1557a-7aef-4fc0-84c2-1de2c07123e8.png) 另附`fs`上下文与版本：
> 
> ![image](https://user-images.githubusercontent.com/29349119/214275057-1af0fc56-a379-4213-bf18-cc2d04aaea2b.png)

更新至 BetterNCM 1.0.0 稳定版 或 nightly。 1.0.0-pre3及以前版本均不包含 mountFile api
