### ISSUE TITLE
[建议]希望增加个自定义图片(网络图片)

### ISSUE THREAD

**Issue by GuaiJieYo** [BetterNCM/BGEnhanced#9]
如题
希望搞个这个

**Comment by GuaiJieYo** [comment]
手动从DevTools里加有点麻烦   XD

**Comment by MicroCBer** [comment]
已完成
![image](https://user-images.githubusercontent.com/66859419/214561282-38410aa5-0f61-402a-a2b9-019c9b208888.png)
![image](https://user-images.githubusercontent.com/66859419/214561294-59a02400-8c6d-413e-bdd4-2d7e7d38f838.png)
